import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import AppProvider from "@/app/app-provider";
import { Suspense } from "react";
import LoadingPage from "@/app/loading";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Curanest",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ToastContainer className="text-base mr-10" position="top-right" />
        <Suspense fallback={<LoadingPage/>}>
          <AppProvider>
            <Providers>{children}</Providers>
          </AppProvider>
        </Suspense>
      </body>
    </html>
  );
}
